apiVersion: v1
kind: ServiceAccount
metadata:
  name: meta-scheduler-sa
  namespace: task04
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meta-scheduler-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/binding", "bindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meta-scheduler-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: meta-scheduler-role
subjects:
  - kind: ServiceAccount
    name: meta-scheduler-sa
    namespace: task04
