apiVersion: apps/v1
kind: Deployment
metadata:
  name: task05
  namespace: task05
  labels:
    app: task05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task05
  template:
    metadata:
      labels:
        app: task05
    spec:
      containers:
        - name: task05
          image: task05:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 100Mi
              cpu: 0.5
            limits:
              memory: 1Gi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: task05-service
  namespace: task05
spec:
  selector:
    app: task05
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
---