apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task05-ingress
  namespace: task05
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.task05.local
  rules:
    - host: api.task05.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: task05-service
                port:
                  number: 80