apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: task05
  namespace: task05
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: task05
  updatePolicy:
    updateMode: InPlaceOrRecreate
