# =========================
# CATALOG DB (StatefulSet)
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalog-db
  namespace: bookrent
  labels:
    app: catalog-db
spec:
  serviceName: catalog-db
  replicas: 1
  selector:
    matchLabels:
      app: catalog-db
  template:
    metadata:
      labels:
        app: catalog-db
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Express"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "1"
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssqldata
        labels:
          app: catalog-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: bookrent
spec:
  selector:
    app: catalog-db
  ports:
    - port: 1433
      targetPort: 1433
---
# =========================
# IDENTITY DB (StatefulSet)
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: identity-db
  namespace: bookrent
  labels:
    app: identity-db
spec:
  serviceName: identity-db
  replicas: 1
  selector:
    matchLabels:
      app: identity-db
  template:
    metadata:
      labels:
        app: identity-db
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Express"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "1"
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssqldata
        labels:
          app: identity-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: identity-db
  namespace: bookrent
spec:
  selector:
    app: identity-db
  ports:
    - port: 1433
      targetPort: 1433
---
# =========================
# RENTING DB (StatefulSet)
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: renting-db
  namespace: bookrent
  labels:
    app: renting-db
spec:
  serviceName: renting-db
  replicas: 1
  selector:
    matchLabels:
      app: renting-db
  template:
    metadata:
      labels:
        app: renting-db
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Express"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "1"
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssqldata
        labels:
          app: renting-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: renting-db
  namespace: bookrent
spec:
  selector:
    app: renting-db
  ports:
    - port: 1433
      targetPort: 1433
---
# =========================
# USER DB (StatefulSet)
# =========================
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: user-db
  namespace: bookrent
  labels:
    app: user-db
spec:
  serviceName: user-db
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Express"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: SA_PASSWORD
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "1"
          volumeMounts:
            - name: mssqldata
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: mssqldata
        labels:
          app: user-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: bookrent
spec:
  selector:
    app: user-db
  ports:
    - port: 1433
      targetPort: 1433
