
# =========================
# ORCHESTRATOR (API GATEWAY + API)
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-service
  namespace: bookrent
  labels:
    app: orchestrator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator-service
  template:
    metadata:
      labels:
        app: orchestrator-service
    spec:
      containers:
        - name: orchestrator-service
          image: bookrent_orchestrator-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
  namespace: bookrent
spec:
  selector:
    app: orchestrator-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: bookrent_catalog-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__CatalogDb
              value: "Server=catalog-sql,1433;Database=CatalogDb;User=sa;Password=Your_SA_Password_123!;TrustServerCertificate=True;MultipleActiveResultSets=true"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: renting-service
  labels:
    app: renting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: renting-service
  template:
    metadata:
      labels:
        app: renting-service
    spec:
      containers:
        - name: renting-service
          image: bookrent_renting-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__RentingDb
              value: "Server=renting-sql,1433;Database=RentingDb;User=sa;Password=Your_SA_Password_123!;TrustServerCertificate=True;MultipleActiveResultSets=true"
---
apiVersion: v1
kind: Service
metadata:
  name: renting-service
spec:
  selector:
    app: renting-service
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: bookrent_user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__UserDb
              value: "Server=user-sql,1433;Database=UserDb;User=sa;Password=Your_SA_Password_123!;TrustServerCertificate=True;MultipleActiveResultSets=true"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: bookrent_identity_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: ConnectionStrings__IdentityDb
              value: "Server=identity-sql,1433;Database=IdentityDb;User=sa;Password=Your_SA_Password_123!;TrustServerCertificate=True;MultipleActiveResultSets=true"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  selector:
    app: identity-service
  ports:
    - port: 80
      targetPort: 8080
